name: flutterapplication
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.0
  google_sign_in: ^7.1.1
  smooth_page_indicator: ^1.2.1
  google_maps_flutter: ^2.6.1
  geocoding: ^2.1.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  http: ^1.2.0
  get: ^4.7.2
  pinput: ^5.0.2
  loading_animation_widget: ^1.3.0
  change_app_package_name: ^1.5.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  audioplayers: ^6.5.1
  flutter_tts: ^4.2.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  geolocator: ^13.0.4
  cupertino_icons: ^1.0.8
  custom_info_window: ^1.0.1
  flutter_map_location_marker: ^9.1.1
  location: ^8.0.1
  flutter_polyline_points: ^3.1.0
  firebase_messaging: ^16.0.4
  collection: ^1.19.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  intl: ^0.19.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sayahat.png
    - assets/avatar.png
    - assets/region.jpeg
    - assets/IMG_5578.JPG
    - assets/Мечеть.jpeg
    - assets/bbb.jpg
    - assets/JOJADOJA.jpeg
    - assets/places.json
    - assets/translations/en.json
    - assets/translations/kk.json
    - assets/translations/ru.json
